version: '3.5'
networks:
    localdev: 
        name: localdev
services:
    main-api:
        build: Tweetbook/
        restart: always
        ports: 
          - "7000:80"
        depends_on:
          - db-server
        networks: 
          - localdev
    db-server:
        image: "nouchka/sqlite3:latest"
        container_name: db-server
       
        ports:
          - "1400:1433"
        networks:
          - localdev